#import "../../temp.typ": *
#show: chpt-note.with()

= Extragalactic Sources
== AGNs
_Active galactic nuclei_ or _AGN_ are observed to be extremely bright sources on the sky, typically across the entire electromagnetic spectrum. Historically the different types of sources say _radio-quiet_ or _radio-loud_ AGN were thought to be physically different objects. However, now it is generally believed that all the different types of AGN we observe stem from the same physical object. This viewpoint is referred to as _unification_. The unified model#footnote[These unfification models can be _strong_ or _weak_ depending on how many fundamental parameters they include. The strongest models say only _orientation_ and _obscuration_ determine the observed differences in AGN.] proposes all AGN are driven by _accretion_ onto a central _supermassive black hole_.#footnote[This typically leads to _high variability_ since black holes are relatively small.] The black hole is surrounded by a hot accretion disk which produces thermal radiation in the optical and UV. Some AGN also produce large _jets_ of relativistic particles carrying mass, energy, momentum, and magnetic fields away from the AGN.#footnote[Why they do this is still a mystery. An explanation could be the _Blandford-Znajek mechanism_ where the central black hole spinning is believed to produce an _EMF_.] The accretion disk also acts to ionise the gas surrounding the black hole. This leads to the creation of two emission regions: the _broad line region_ and the _narrow line region_. The main difference being their velocities leading to different amounts of Doppler shift. Lastly an _obscuring torus_ compoes of dust surrounds the central region. This torus is why various AGN can appear different even though they are truly the same object. The torus also absorbs UV radiation from the accretion disk and re-emits it in the infrared.#footnote[Typically referred to as the _infrared bump_.]

Classification of AGNs is quite boring and needlessly complicated. We simply mention that _blazars_ are AGN whose jets point toward us. This leads to very bright emissions across the entire electromagnetic spectrum, and therefore these are nice astrophysical laboratories. Some blazars have featureless, boring spectra, while others show strong, broad emission lines. The boring ones are called _BL Lacs_ and the exciting ones are called _FSRQs_.

== Black holes
For our purposes a black hole is a region of space where a large amount of mass is concentration in a very small volume. This leads to a very strong gravitational field which even light cannot escape. The boundary surrounding the black hole is referred to as the _event horizon_.#footnote[When something crosses the horizon it is destined to reach the center. However, for an outside observer nothing can ever cross the horizon.] These objects primarily form when massive stars collapse. However, very large black holes are believed to form in other ways. We are interested in black holes since these objects have very large gravitational fields on small scales. We might therefore get clues as to what a theory of quantum gravity should look like by studying black holes.

Hawking showed quantum effects near the horizon cause black holes to emit radiation, which we call _Hawking radiation_. This implies black holes have a temperature#footnote[The _Hawking temperature_.] and will evaporate. This is a problem since radiation is _thermal_ by definition, meaning when the black hole evaporates we evolve from a _pure_ state $ket(Psi)_"BH"$ to a _mixed_ state $ket(Psi)_"radiation"$. This violates _unitarity_ and is therefore a problem. We typically call this the _information paradox_ since information is lost.

== Blazars
As mentioned blazars are AGN whose jets point toward us. These AGN are radio-loud, show high variability, strong optical polarisation, and the familiar SED with a high-energy and low-energy peak. The low-energy peak is believed to be caused by synchrotron emission#footnote[The position of the peak further classifies blazars as _low synchrotron peak_ or _LSP_ blazars, _ISP_ blazars, and _HSP_ blazars.] The high-energy peak is believed to be caused by inverse Compton emission. However, the latter is somewhat disputed. Some believe it is _leptonic_ with $e^-$ scattering with $gamma_"synch"$ and $gamma_"ext"$ from the BLR region. These are called synchrotron self-Compton and external Compton respectively. Others believe it is _hadronic_ with $e^-$ and $p$ being accelerated to high energies with $p -> gamma + pi$. The emission is then dominated by _proton synchrotron_ and external Compton. We typically observe the X-ray and $gamma$-ray emissions to be correlated as would be predicted by leptonic models. As such these are favored.#footnote[Of course exceptions exist since the Universe is annoying.]

Due to relativistic beaming then the flux of blazars is heavily amplified.

== $gamma$-ray bursts
_$gamma$-ray bursts_ or _GRBs_ are essentially extremely powerful explosions. These flashes of high-energy radiation are produced in _catastrophic events_ such as neutron-star mergers. When they occur they are the brightest sources in the Universe. We distinguish between _short_ and _long_ GRBs.#footnote[Lasting shorter or longer than two seconds.] They are generally believed to arise from relativistic jets moving very at speeds very, very close to the speed of light. As expected we mostly observe the long duration GRBs. These are often formed when massive stars collapse and become a supernovae. Therefore supernovae are usually seen after a long GRB. The emission of GRBs is across the entire electromagnetic spectrum and is generally believed to be caused by synchrotron emissions. However, at very high-energies additional mechanisms are required such as inverse Compton scattering leading to $gamma$-rays.

== The EBL
When $gamma$-rays travel toward us they can interact with photons on the way and pair-produce whenever enough energy is available. The wavelength which TeV $gamma$-rays mostly interact with is given by
$
  lambda tilde.eq^"Bethe-Heitler" 1.21 mu"m" (E/"TeV")
$
where the _Bethe-Heitler_ cross sections peaks for $beta_"max" tilde.eq 0.7$. This pair-production leads to a loss of $gamma$-ray photons and we observe this as the spectrum being attenuated.

This implies the background radiation fields most relevant for attenuation are the optical and infrared backgrounds. These are typically referred to as the _extragalactic background light_ or _EBL_. The optical background is caused by starlight while the infrared background is caused by dust absorbing starlight and re-emitting is as thermal radiation. The EBL is very hard to measure by simply counting sources and summing all contributions. We can instead use e.g. blazars and use a fit similar to
$
  F(E) = underbracket(F_"intrinsic" (E,theta), "given by blazar") overbracket(e^(-alpha tau(E, z)), "given by EBL model")
$
Which is in many ways simpler. We can therefore use observations of AGN to constrain the EBL.
