//**** init-ting
#import "@preview/physica:0.9.8": *
#import "chpt-temp.typ": *

#show: thmrules.with(qed-symbol: $square$)
#show: chpt-note.with()

= Galaxies
== Simplistic model
Stars tend to be contained within galaxies which are small concentrations of stars and interstellar gas within a larger halo. We define the luminosity function
$
  Phi(L) dd(L) = Phi^* (L/L^*)^alpha exp(- L/L^*) dd(L)/L^*
$
telling us the number density of galaxies with luminosity in the range $L -> L + dd(L)$. So galaxies with $L > L^*$ are rare since they need to be large which typically requires cannibalizing other galaxies.

We consider a simple model of galaxy formation. We analyse a spherical overdense region at $t_(r m)$. This eventually becomes a galaxy. The mass of the region is
$
  M = (4 pi)/3 rho_m (t) [1 + delta(t)]R(t)^3
$
with $rho_m (t) = rho_(m,0) (1+z)^3$. At $t_(r m)$ we have $delta(t_"rm") = delta_"rm" << 1$ and the region's expansion is dominated by Hubble flow. Eventually it begins collapsing when $delta(t_"coll") tilde 1$. With $delta prop a prop t^(2\/3)$ we approximate $t_"coll" tilde delta_"rm"^(-3\/2) t_"rm"$ or $ 1+z_"coll" tilde delta_"rm" (1+z_"rm") $
When it collapses we have
$
  overline(rho) (t_"coll") tilde 2 rho_m (t_"coll") tilde 2 rho_(m,0) (1+z_"coll")^3
$
After collapsing it reaches equilibrium with $R_"halo" tilde R(t_"coll")\/2$. We treat the gas as ideal so
$
  P_"gas" = (rho_"gas" k_B T_"gas")/(mu)
$
With equilibrium when
$
  dv(P_"gas", r) = - (G M(r) rho_"gas" (r))/r^2
$
Then
$
  M(r) = (k_B T_"gas" (r) r)/(G mu) [- dv(ln rho_"gas", ln r) - dv(ln T_"gas", ln r)]
$
Assuming $rho_"gas" prop r^(-beta)$ and a uniform temperatur $T_"gas"$ with $r = R_"halo"$ and $M(r) = M_"tot"$ gives
$
  k_B T_"gas" = (G M_"tot" mu)/(beta R_"halo")
$
With
$
  R_"halo" = ((3 M_"tot")/(4 pi overline(rho)_"halo"))^(1\/3)
$
we have
$
  k T_"gas" = 4/beta (pi/3)^(1\/3) G mu rho_(m,0)^(1\/3) M_"tot"^(2\/3) (1+z_"coll")
$
This depends on $M_"tot"$ which is problematic for massive halos, since a galaxy needs to radiate heat to cool down. For galaxies with $M_"tot" > 10^12 M_dot.circle$ it is very unlikely they would have had enough time to cool. However, this model is very simplistic and in reality it is more complicated. But this does explain why intergalactic dust does not collapse.

== Active galactic nuclei
By observation many young and remote galaxies have very high amounts of activity. We call these active galaxies. The engine driving this activity is called the active galactic nuclei or AGN. These are special since they emit light at all wavelengths. Generally their spectra can be decomposed into thermal- (the blue- and infrared bumps) and nonthermal sources. The bumps are believed to be caused by a thick accretion disk (blue) and dust grains (infrared). They also show a turnover at low frequencies which is steep for radio quiet AGN and steeper for radio loud AGN. Typically broad-line emission is variable, while narrow-line emission is non-variable.

There are many different types of AGN depending on what their spectra show. We will not go through these since it is believed they all stem from the same object. Typically called the unified model. The idea is that all AGN are fueled by accretion onto a central supermassive black hole, with the various classifications being orientational.

Due to the high variability of AGNs their size must be $R tilde 10 "AU"$ which is very small. We can try to estimate the mass by using the Eddington limit
$
  L_"ed" = (4 pi G c)/overline(kappa) M tilde 1.5 times 10^31 "W" (M/M_dot.circle)
$
For a quasar with $L =5 times 10^(39) "W"$ this gives a minimal mass
$
  M = 3.3 times 10^8 M_dot.circle
$
which is enourmous. This suggests that AGN are supermassive black holes. The luminosity generated by such a black hole can be written as
$
  L_"disk" = eta dot(M) c^2
$
And the disk temperature can be written as ($R = G M\/c^2$)
$
  T_"disk" = ((3 c^6 dot(M))/(8 pi sigma G^2 M^2))^(1\/4)
$
We define $f_"ed" equiv L_"disk"\/L_"ed"$ giving
$
  T_"disk" = ((3 c^5 f_"ed")/(2 overline(kappa) sigma G M eta))^(1\/4)
$
so $T_"disk" prop M^(-1\/4)$. Modelling the accretion disk is difficult, one suggestion is a three-part disk. In the first part, which is closest to the black hole, radiation pressure exceeds gas pressure leading to a thick, hot disk. Outside this is a thinner disk supported by gas pressure, which becomes thicker at larger distances. This flaring means it can be irradiated by the thick disk. Beyond this the disk breaks up into smaller clouds.

The continuous synchrotron spectra of AGNs could be described by the magnetic field of the black hole. The ionized disk rotating could also induce a large electric field, leading to radiation. Blandford-Znajek suggest that the black hole itself acts like a spinning conductor, which creates an emf by taking rotational energy from the black hole. X-rays (and gamma-rays) can also be created by low-energy photons inverse Compton scattering with relativistic electrons. The generation of charged particles, their acceleration and subsequent ejection is thought to be the origin of jets and accompanying radio lobes.

The accretion disk, obscuring torus and jets all contribute to the continuum spectra of AGNs. This is essentially a power law $F_nu prop nu^alpha$.

The broad- and narrow emission lines of AGN spectra are the result of photoionization by the continuum radiation. They are formed in the broad-line and narrow-line regions respectively. The broad-line region is close to the center consists of clumpy partially ionized clouds of gas. These orbit the black hole very quickly leading to doppler broadening. The unified model postulates that a large optically thick obscuring torus of gas and dust surrounds the cloud of gas in the broad-line region. This torus acts to conceal the broad-line region and the central source from direct view. Outside this torus is the narrow-line region and is probably composed of a spherical-ish distribution of clouds. Some of these can be ionized by the center, others can not due to the torus.

So in a typical spectrum we would have a continuum with the addition of the broad- and narrow emission lines.

== As probes
Quasars have very high redshift and are thus very far away. They can be used as probes since their light is affected by everything between us and them. One way this is done is through gravitational lensing. Another way is the Lyman-$alpha$ forest. High redshift quasars show many narrow absorption lines superimposed on the quasar's continuum spectrum. These come when light from a quasar passes through material along the line of sight. If this material is far from us then these lines appear redshifted. So if light passes through multiple things we will see multiple lines redshifted by different amounts. The Lyman-$alpha$ forest is a dense collection of hydrogen absorption lines. Metals can also lead to absorption lines (from galaxies, star formation, etc.). And both types are generally found in the UV, since the material is moving at very high speeds. What one observes is a very strong Lyman-$alpha$ emission line by the quasar itself, and then many, many Lyman-$alpha$ absorption lines at shorter wavelengths (meaning smaller redshifts). One can combine this with lensing to deduce things like size of intergalactic clouds, etc.
